# plot_yaw.py

import glob
import re
import pandas as pd
import matplotlib.pyplot as plt
# Find all CSV files generated by the simulator
files = sorted(glob.glob("csvs/Trailer_Position_and_Orientation_Over_Time_For_Pull_*.csv"))

if not files:
    print("No simulation CSV files found.")
    exit()

plt.figure(figsize=(10, 6))

for file in files:
    df = pd.read_csv(file)

    # Extract pull value from filename
    match = re.search(r"Pull_(\d+\.?\d*)", file)
    if match:
        pull = float(match.group(1))
        label = f"{pull:.0f} N"
    else:
        label = file

    plt.plot(df["time"], df["hitch_yaw"], linewidth=2, label=label)

plt.title("Trailer Hitch Yaw vs Time")
plt.xlabel("Time (s)")
plt.ylabel("Yaw (degrees)")
plt.grid(True)
plt.legend(title="Pull")
plt.tight_layout()
plt.show()