# plot_yaw.py

import glob
import re
import pandas as pd
import matplotlib.pyplot as plt

# Find all CSV files generated by the simulator
files = sorted(glob.glob("csvs/Trailer_Position_and_Orientation_Over_Time_For_Impulse_*.csv"))

if not files:
    print("No simulation CSV files found.")
    exit()

plt.figure(figsize=(10, 6))

for file in files:
    df = pd.read_csv(file)

    # Extract impulse value from filename
    match = re.search(r"Impulse_(\d+\.?\d*)", file)
    if match:
        impulse = float(match.group(1))
        label = f"{impulse:.0f} N·s"
    else:
        label = file

    plt.plot(df["time"], df["hitch_yaw"], linewidth=2, label=label)

plt.title("Trailer Hitch Yaw vs Time")
plt.xlabel("Time (s)")
plt.ylabel("Yaw (degrees)")
plt.grid(True)
plt.axvline(x=1.5, color='red', linestyle=':', linewidth=2, label='Impulse Applied')
plt.legend(title="Impulse")
plt.tight_layout()
plt.show()